<?php

/*
|--------------------------------------------------------------------------
| Website Texts Registry
|--------------------------------------------------------------------------
|
| Every user-facing text on the public website is registered here.
| Keys are grouped by page/section. The "keys" value is the default
| fallback shown when an admin has not customized it yet.
|
| Blade views read these via the global text('key') helper.
| The admin panel edits them through GET/PUT /api/admin/website-texts.
|
*/

return [

    'brand' => [
        'label' => 'Brand & Navigation',
        'icon'  => 'auto_awesome',
        'keys'  => [
            'brand.prefix'   => 'Teacher',
            'brand.name'     => "Roya's",
            'brand.suffix'   => 'Stars',
            'nav.home'       => 'Home',
            'nav.topics'     => 'Topics',
            'nav.exam'       => 'Exam',
            'nav.achievements' => 'Achievements',
            'nav.badges'     => 'Badges',
            'nav.profile'    => 'Profile',
            'nav.login'      => 'Log In',
            'nav.signup'     => 'Sign Up',
        ],
    ],

    'home' => [
        'label' => 'Homepage',
        'icon'  => 'home',
        'keys'  => [
            'home.page_title'      => "Teacher Roya's Stars — Learn English the Fun Way",
            'home.hero.tag'        => 'Online Learning Platform',
            'home.hero.title_1'    => 'Master English',
            'home.hero.title_hl'   => 'One Star',
            'home.hero.title_2'    => 'at a Time',
            'home.hero.desc'       => 'Interactive lessons, engaging quizzes, and a gamified star system — making English learning fun and effective for every student in Azerbaijan.',
            'home.hero.stat_1'     => 'Stars Earned',
            'home.hero.stat_2'     => 'Active Learners',
            'home.hero.stat_3'     => 'Quizzes',
            'home.hero.scroll'     => 'Scroll',
            'home.start.tag'       => 'Getting Started',
            'home.start.title_1'   => 'Three Simple',
            'home.start.title_hl'  => 'Steps',
            'home.start.desc'      => 'Begin your English journey in minutes. No complicated setup — just pure learning and fun.',
            'home.step_1_title'    => 'Create Account',
            'home.step_1_desc'     => "Sign up with your email or phone. It's completely free and only takes a moment.",
            'home.step_2_title'    => 'Pick a Topic',
            'home.step_2_desc'     => 'Choose from grammar, vocabulary, reading, and exam prep. Learn entirely at your own pace.',
            'home.step_3_title'    => 'Earn Stars',
            'home.step_3_desc'     => 'Complete lessons and quizzes to collect stars, track progress, and stay motivated.',
            'home.features.tag'    => 'Features',
            'home.features.title_1' => 'Everything You Need to',
            'home.features.title_hl' => 'Excel',
            'home.features.desc'   => 'A comprehensive platform designed for Azerbaijani students mastering English.',
            'home.feature_1_title' => 'Interactive Lessons',
            'home.feature_1_desc'  => 'Video-based lessons with real-world examples and visual aids that make complex grammar simple and intuitive.',
            'home.feature_2_title' => 'Smart Quizzes',
            'home.feature_2_desc'  => 'Topic-based quizzes with instant feedback. Every wrong answer is a learning opportunity.',
            'home.feature_3_title' => 'Gamified Rewards',
            'home.feature_3_desc'  => 'Earn stars for lessons, perfect scores, and daily streaks. Achievements turn studying into a challenge.',
            'home.feature_4_title' => 'Exam Preparation',
            'home.feature_4_desc'  => 'Grade 9 and Final exam practice with realistic mock tests. Build confidence before exam day.',
            'home.feature_5_title' => 'Bilingual Support',
            'home.feature_5_desc'  => "Content available in Azerbaijani, English, and Russian. Learn in the language you're most comfortable with.",
            'home.feature_6_title' => 'Progress Tracking',
            'home.feature_6_desc'  => 'Dashboard with completed lessons, quiz scores, star collection — all your stats in one place.',
            'home.teacher.tag'     => 'Your Teacher',
            'home.teacher.title_1' => 'Meet',
            'home.teacher.title_hl' => 'Teacher Roya',
            'home.teacher.desc'    => 'Passionate educator dedicated to making English accessible for every Azerbaijani student.',
            'home.teacher.quote'   => 'I believe every student has the potential to shine. My goal is to create a learning environment where English feels less like a subject and more like an adventure — complete with stars to reward every step forward.',
            'home.teacher.name'    => 'Teacher Roya',
            'home.teacher.role'    => 'Founder & Lead Instructor',
            'home.cta.tag'         => 'Start Today',
            'home.cta.title'       => 'Ready to Become a Star?',
            'home.cta.desc'        => 'Join hundreds of students already learning with Teacher Roya. Your English adventure starts here — for free.',
            'home.cta.btn_1'       => 'Create Free Account',
            'home.cta.btn_2'       => 'I Already Have an Account',
        ],
    ],

    'topics' => [
        'label' => 'Topics Page',
        'icon'  => 'rocket_launch',
        'keys'  => [
            'topics.page_title'        => 'Topics - Learning Universe',
            'topics.hero.tag'          => 'Learning Galaxies',
            'topics.hero.title'        => 'Your Learning Universe 🌟',
            'topics.hero.desc'         => 'Embark on your journey through the grammar galaxies. Every topic mastered brings you closer to earning Star XP badges!',
            'topics.search_placeholder' => 'Search topics...',
            'topics.showing'           => 'Showing {count} of {total} Topics',
            'topics.card_badge'        => 'Topic {num}',
            'topics.card_desc'         => 'Grammar Module',
            'topics.empty_title'       => 'No Topics Found',
            'topics.empty_no_query'    => 'No topics available yet.',
            'topics.empty_search'      => 'No topics match your search query.',
            'topics.sidebar_level'     => 'Star Explorer Level',
            'topics.sidebar_level_desc' => 'Complete topics to unlock new ranks',
            'topics.sidebar_level_label' => 'Level {level}',
            'topics.sidebar_stars'     => '{count} Stars',
            'topics.sidebar_badges'    => 'View Badges',
            'topics.sidebar_login'     => 'Log In to Save Progress',
            'topics.sidebar_exam_title' => 'Grade Final Exams',
            'topics.sidebar_exam_desc' => 'Test your full knowledge across grade levels',
            'topics.sidebar_exam_btn'  => 'Take Final Exam',
            'topics.sidebar_tip_title' => 'Daily Learning Tip',
            'topics.sidebar_tip_desc'  => 'Study 1 topic and complete its knowledge check quiz every day to keep your 7-day streak active!',
        ],
    ],

    'subtopics' => [
        'label' => 'Topic Detail (Lessons)',
        'icon'  => 'menu_book',
        'keys'  => [
            'subtopics.page_title'      => '{topic} - Lessons & Learning Path',
            'subtopics.breadcrumb_topics' => 'Topics',
            'subtopics.breadcrumb_subject' => 'English',
            'subtopics.hero_desc'       => 'Explore {count} interactive lessons to master this topic and earn Star XP points!',
            'subtopics.hero_lessons'    => 'Lessons',
            'subtopics.hero_earn'       => 'Earn Star XP',
            'subtopics.search_placeholder' => 'Search lessons in {topic}...',
            'subtopics.showing'         => 'Showing {count} of {total} Lessons',
            'subtopics.lesson_badge'    => 'Lesson {num}',
            'subtopics.lesson_recommended' => 'Recommended Next',
            'subtopics.lesson_start'    => 'Start Learning',
            'subtopics.lesson_study'    => 'Study Lesson',
            'subtopics.empty_title'     => 'No Lessons Found',
            'subtopics.empty_search'    => 'Try clearing your search query to see all lessons.',
            'subtopics.empty_none'      => 'No lessons have been added to this topic yet.',
            'subtopics.sidebar_title'   => 'Topic Overview',
            'subtopics.sidebar_subject' => 'English',
            'subtopics.sidebar_total'   => 'Total Lessons',
            'subtopics.sidebar_xp'      => 'XP Potential',
            'subtopics.sidebar_back_title' => 'All Topics',
            'subtopics.sidebar_back_desc' => 'Return to main learning path',
        ],
    ],

    'lesson' => [
        'label' => 'Lesson Page',
        'icon'  => 'smart_display',
        'keys'  => [
            'lesson.page_title'        => '{name} - Lesson',
            'lesson.back_to'           => 'Back to {topic}',
            'lesson.breadcrumb_default' => 'Lesson',
            'lesson.video_count'       => '{count} Video',
            'lesson.quiz_questions'    => '{count} Quiz Questions',
            'lesson.player_title'      => 'Interactive Lesson Player',
            'lesson.video_default'     => 'Lesson Video',
            'lesson.player_hd'         => 'HD 1080p',
            'lesson.notes_title'       => 'Lesson Notes',
            'lesson.empty_title'       => 'No Media Content Available',
            'lesson.empty_desc'        => 'Content is being prepared for this lesson. Check back soon!',
            'lesson.rate_title'        => 'Rate This Lesson',
            'lesson.rate_already'      => 'Siz artıq bu dərsə rəy vermisiniz',
            'lesson.rate_prompt'       => 'How was your learning experience?',
            'lesson.rate_feedback_label' => 'Your Feedback (Optional)',
            'lesson.rate_feedback_placeholder' => 'Share your thoughts about this lesson...',
            'lesson.rate_submit'       => 'Submit Feedback',
            'lesson.quiz_title'        => 'Knowledge Check',
            'lesson.quiz_questions_count' => 'Questions',
            'lesson.quiz_earn'         => 'Earn XP',
            'lesson.quiz_start'        => 'Start Quiz',
            'lesson.back_topic_desc'   => 'See all lessons in this topic',
            'lesson.rate_thanks'       => 'Thank You!',
            'lesson.rate_success_desc' => 'Your feedback has been saved successfully.',
            'lesson.rate_error_generic' => 'Something went wrong.',
            'lesson.rate_error_retry'  => 'Something went wrong. Please try again.',
        ],
    ],

    'quiz' => [
        'label' => 'Quiz (Solve)',
        'icon'  => 'quiz',
        'keys'  => [
            'quiz.page_title'         => '{name} - Quiz',
            'quiz.badge'              => 'Practice Quiz',
            'quiz.lesson'             => 'Lesson',
            'quiz.progress'           => 'Progress',
            'quiz.question'           => 'Question {num}',
            'quiz.confirm'            => 'Confirm Answer',
            'quiz.open_placeholder'   => 'Type your answer here...',
            'quiz.previous'           => 'Previous',
            'quiz.next'               => 'Next Question',
            'quiz.submit'             => 'Submit & Finish',
            'quiz.checking'           => 'Checking...',
            'quiz.correct_title'      => 'Correct!',
            'quiz.correct_sub'        => 'Your answer is right.',
            'quiz.incorrect_title'    => 'Incorrect!',
            'quiz.incorrect_sub'      => 'The correct answer is highlighted in green.',
            'quiz.incorrect_open_sub' => 'The expected answer is shown on the result page.',
            'quiz.explanation_video'  => 'İzah Videosu',
        ],
    ],

    'quiz_result' => [
        'label' => 'Quiz Result',
        'icon'  => 'fact_check',
        'keys'  => [
            'quiz_result.page_title'   => 'Quiz Result - {name}',
            'quiz_result.badge'        => 'Quiz Summary & Assessment',
            'quiz_result.title_fallback' => 'Quiz Completed',
            'quiz_result.desc'         => 'Awesome effort! Review your answers below to strengthen your grammar mastery.',
            'quiz_result.score'        => 'Score',
            'quiz_result.correct_of'   => '{count} of {total} Correct',
            'quiz_result.breakdown'    => 'Question Breakdown',
            'quiz_result.filter_all'   => 'All',
            'quiz_result.filter_correct' => 'Correct',
            'quiz_result.filter_wrong' => 'Wrong',
            'quiz_result.question'     => 'Question #{num}',
            'quiz_result.correct_badge' => 'Correct',
            'quiz_result.incorrect_badge' => 'Incorrect',
            'quiz_result.question_content' => 'Question Content',
            'quiz_result.your_answer'  => 'Your Answer:',
            'quiz_result.no_answer'    => 'No Answer',
            'quiz_result.correct_answer' => 'Correct Answer:',
            'quiz_result.explanation_video' => 'İzah Videosu',
            'quiz_result.rewards'      => 'Rewards Earned',
            'quiz_result.xp_stars'     => '+{count} XP Stars',
            'quiz_result.rewards_desc' => 'Great job completing this quiz! Your star score has been updated in your profile.',
            'quiz_result.retake'       => 'Retake Quiz',
            'quiz_result.back_topic'   => 'Back to Topic',
        ],
    ],

    'exam' => [
        'label' => 'Exam Zone',
        'icon'  => 'assignment',
        'keys'  => [
            'exam.page_title'         => 'Exam Zone',
            'exam.badge'              => 'Exam Zone',
            'exam.grade_title'        => 'Choose Your Grade',
            'exam.grade_subtitle'     => 'Select your grade to see the exams waiting for you.',
            'exam.grades_label'       => 'Grades',
            'exam.exams_label'        => 'Exams',
            'exam.title'              => 'Test Your Knowledge',
            'exam.subtitle'           => 'Prove your mastery! Each exam brings you closer to becoming a grammar galaxy legend.',
            'exam.questions_label'    => 'Questions',
            'exam.empty'              => 'No exams available yet',
            'exam.card_exams_count'   => '{count} Exams',
            'exam.card_grade_desc'    => 'Select this grade to view its exams.',
            'exam.card_available'     => 'Available now',
            'exam.back_all_grades'    => 'All Grades',
            'exam.card_questions'     => 'questions',
            'exam.card_min'           => 'min',
            'exam.card_best'          => 'Best Score: {score}%',
            'exam.card_not_attempted' => 'Not attempted',
            'exam.reward_title'       => 'Star Collector',
            'exam.reward_desc'        => 'Pass exams to earn stars and unlock new achievements!',
            'exam.learn_more'         => 'Learn More',
        ],
    ],

    'exam_detail' => [
        'label' => 'Exam Detail',
        'icon'  => 'description',
        'keys'  => [
            'exam_detail.page_title'  => '{name} - Exam Detail',
            'exam_detail.back'        => 'Back to Exams',
            'exam_detail.badge'       => '{grade} Exam',
            'exam_detail.questions'   => 'questions',
            'exam_detail.last_score'  => 'Last Score',
            'exam_detail.start'       => 'Start Exam',
            'exam_detail.retake'      => 'Retake Exam',
            'exam_detail.min'         => 'min',
            'exam_detail.view_result' => 'View Last Result',
        ],
    ],

    'exam_solve' => [
        'label' => 'Exam (Solve)',
        'icon'  => 'edit_note',
        'keys'  => [
            'exam_solve.page_title'   => '{name} - Exam',
            'exam_solve.badge'        => 'Exam',
            'exam_solve.badge_grade'  => '{grade} Exam',
            'exam_solve.progress'     => 'Progress',
            'exam_solve.questions'    => 'questions',
            'exam_solve.question'     => 'Question {num}',
            'exam_solve.open_placeholder' => 'Type your answer here...',
            'exam_solve.previous'     => 'Previous',
            'exam_solve.next'         => 'Next Question',
            'exam_solve.submit'       => 'Submit & Finish',
            'exam_solve.all_visible_hint' => 'All questions are shown on this page — answer them all, then submit.',
            'exam_solve.min'          => 'min',
        ],
    ],

    'exam_result' => [
        'label' => 'Exam Result',
        'icon'  => 'emoji_events',
        'keys'  => [
            'exam_result.page_title'   => 'Exam Result - {name}',
            'exam_result.badge'        => 'Exam Report',
            'exam_result.badge_grade'  => '{grade} Exam Report',
            'exam_result.title_fallback' => 'Exam Completed',
            'exam_result.desc'         => 'Comprehensive performance evaluation. Review your answers below to strengthen your knowledge.',
            'exam_result.score'        => 'Score',
            'exam_result.correct_of'   => '{count} of {total} Correct',
            'exam_result.passed'       => 'PASSED',
            'exam_result.not_passed'   => 'NOT PASSED',
            'exam_result.breakdown'    => 'Question Breakdown',
            'exam_result.filter_all'   => 'All',
            'exam_result.filter_correct' => 'Correct',
            'exam_result.filter_wrong' => 'Wrong',
            'exam_result.question'     => 'Question #{num}',
            'exam_result.correct_badge' => 'Correct',
            'exam_result.incorrect_badge' => 'Incorrect',
            'exam_result.question_content' => 'Question Content',
            'exam_result.your_answer'  => 'Your Answer:',
            'exam_result.no_answer'    => 'No Answer',
            'exam_result.correct_answer' => 'Correct Answer:',
            'exam_result.explanation_video' => 'İzah Videosu',
            'exam_result.rewards'      => 'Exam Bonus',
            'exam_result.xp_stars'     => '+{count} XP Stars',
            'exam_result.rewards_desc' => 'Excellent effort on your exam! Stars have been added to your profile.',
            'exam_result.retake'       => 'Retake Exam',
            'exam_result.back_exams'   => 'Back to Exams',
        ],
    ],

    'achievements' => [
        'label' => 'Achievements & Leaderboard',
        'icon'  => 'military_tech',
        'keys'  => [
            'achieve.page_title'        => 'Achievements & Star Leaderboard',
            'achieve.level_label'       => 'Explorer',
            'achieve.badge'             => 'Star Rewards Hub',
            'achieve.title'             => 'Achievements & Rankings 🌟',
            'achieve.desc'              => 'Earn Star points by completing quizzes and lessons. Monthly stars reset on the last day at 23:59!',
            'achieve.all_time'          => 'All-Time Stars',
            'achieve.monthly'           => 'Monthly Stars',
            'achieve.filter_title'      => 'Monthly Cycle & Historical Rankings',
            'achieve.filter_desc'       => 'Monthly stars reset on the last day of each month at 23:59',
            'achieve.filter_period'     => 'Period:',
            'achieve.tab_achievements'  => 'My Achievements',
            'achieve.tab_leaderboard'   => 'Star Leaderboard 🏆',
            'achieve.timeline_title'    => 'Recent Activity Timeline',
            'achieve.timeline_latest'   => 'Latest Unlocks',
            'achieve.star_default_name' => 'Star Award',
            'achieve.star_default_desc' => 'Awarded for exceptional learning progress!',
            'achieve.unlocked'          => 'Unlocked',
            'achieve.recently'          => 'Recently',
            'achieve.empty_title'       => 'No Achievements For Selected Period',
            'achieve.empty_desc'        => 'Solve quizzes and exams in this period to claim your Star Badges!',
            'achieve.gallery_title'     => 'Badges & Trophies Gallery',
            'achieve.filter_all'        => 'All',
            'achieve.filter_unlocked'   => 'Unlocked',
            'achieve.filter_locked'     => 'Locked',
            'achieve.badge_unlocked'    => 'Unlocked ✓',
            'achieve.badge_locked'      => 'Locked',
            'achieve.badge_default_desc' => 'Complete learning milestones to claim this badge.',
            'achieve.stars'             => 'Stars',
            'achieve.place_2'           => '2nd Place',
            'achieve.champion'          => 'Champion',
            'achieve.place_3'           => '3rd Place',
            'achieve.you'               => 'YOU',
            'achieve.level_explorer'    => 'Level {level} Explorer',
            'achieve.sidebar_title'     => 'Quick Explorer Stats',
            'achieve.sidebar_badges'    => 'Badges Unlocked',
            'achieve.sidebar_period'    => 'Period Stars',
            'achieve.sidebar_quizzes'   => 'Quizzes Done',
            'achieve.sidebar_exams'     => 'Exams Taken',
            'achieve.cta_title'         => 'Earn More Stars!',
            'achieve.cta_desc'          => 'Complete quizzes and lessons to climb up the leaderboards.',
            'achieve.cta_btn'           => 'Explore Topics',
        ],
    ],

    'profile' => [
        'label' => 'Profile Page',
        'icon'  => 'person',
        'keys'  => [
            'profile.page_title'        => 'My Profile',
            'profile.name_fallback'     => 'Star Student',
            'profile.email_fallback'    => 'student@example.com',
            'profile.avatar_edit_title' => 'Fotoşəkil Yüklə / Dəyiş',
            'profile.theme_default'     => 'Default',
            'profile.theme_pink'        => 'Pink',
            'profile.theme_yellow'      => 'Yellow',
            'profile.theme_green'       => 'Green',
            'profile.theme_red'         => 'Red',
            'profile.header_stars'      => 'Ulduz XP',
            'profile.info_title'        => 'Şəxsi Məlumatlar',
            'profile.info_desc'         => 'Profil məlumatlarınızı yeniləyin',
            'profile.label_name'        => 'Ad və Soyad',
            'profile.placeholder_name'  => 'Adınız',
            'profile.label_email'       => 'E-poçt',
            'profile.placeholder_email' => 'yaz@example.com',
            'profile.label_phone'       => 'Telefon',
            'profile.placeholder_phone' => '+994 XX XXX XX XX',
            'profile.label_school'      => 'Məktəb',
            'profile.placeholder_school' => 'Məktəbin adı',
            'profile.label_city'        => 'Şəhər / Rayon',
            'profile.placeholder_city'  => 'Şəhər Seçin',
            'profile.label_grade'       => 'Sinif',
            'profile.placeholder_grade' => 'Sinif Seçin',
            'profile.label_birth'       => 'Doğum Tarixi',
            'profile.save'              => 'Yadda Saxla',
            'profile.password_title'    => 'Şifrəni Dəyiş',
            'profile.password_desc'     => 'Şifrəniz minimum 8 simvoldan ibarət olmalıdır',
            'profile.label_current_pass' => 'Cari Şifrə',
            'profile.label_new_pass'    => 'Yeni Şifrə',
            'profile.label_confirm_pass' => 'Yeni Şifrənin Təkrarı',
            'profile.password_update'   => 'Şifrəni Yenilə',
            'profile.achievements_title' => 'Son Nailiyyətlər',
            'profile.achievements_desc' => 'Qazandığınız son ulduz mükafatları',
            'profile.logout'            => 'Çıxış Et',
            'profile.avatar_upload_title' => 'Profil Fotoşəkili Yüklə',
            'profile.avatar_preview'    => 'Fotoşəkil Önizləməsi',
            'profile.avatar_select'     => 'Kompüter və ya Telefondan Şəkil Seçin',
            'profile.avatar_compress'   => '⚡ Şəkil avtomatik olaraq 256x256 WebP formatında sıxlaşdırılacaq (~15KB).',
            'profile.avatar_preset'     => '🌟 Və ya Hazır İkon Seçin (4x4)',
        ],
    ],

    'login' => [
        'label' => 'Login Page',
        'icon'  => 'login',
        'keys'  => [
            'login.page_title'       => 'Login',
            'login.brand_prefix'     => 'Teacher',
            'login.brand_name'       => "Roya's",
            'login.brand_suffix'     => 'Stars',
            'login.subtitle'         => 'Your journey to the stars starts here.',
            'login.welcome'          => 'Welcome Back',
            'login.credentials'      => 'Please enter your credentials',
            'login.email'            => 'Email Address',
            'login.email_placeholder' => 'example@roya.edu',
            'login.password'         => 'Password',
            'login.forgot'           => 'Forgot?',
            'login.login_now'        => 'Login Now',
            'login.no_account'       => "Don't have an account?",
            'login.signup_cta'       => "Sign up for Teacher Roya's Stars",
            'login.hub_student'      => 'Student Hub',
            'login.hub_rewards'      => 'Star Rewards',
        ],
    ],

    'signup' => [
        'label' => 'Signup Page',
        'icon'  => 'person_add',
        'keys'  => [
            'signup.page_title'      => 'Sign Up',
            'signup.title'           => 'Join the Galaxy',
            'signup.subtitle'        => 'Start your celestial learning journey today.',
            'signup.full_name'       => 'Full Name',
            'signup.name_placeholder' => 'Enter your full name',
            'signup.phone'           => 'Phone Number',
            'signup.city'            => 'City',
            'signup.select_city'     => 'Select City',
            'signup.grade'           => 'Grade',
            'signup.select_grade'    => 'Select Grade',
            'signup.email'           => 'Email Address',
            'signup.email_placeholder' => 'your@email.com',
            'signup.password'        => 'Secure Password',
            'signup.confirm_password' => 'Confirm Password',
            'signup.match_error'     => 'Passwords do not match',
            'signup.btn'             => 'Sign Up Now',
            'signup.has_account'     => 'Already have an account?',
            'signup.login'           => 'Log In',
        ],
    ],

    'pending' => [
        'label' => 'Pending Approval',
        'icon'  => 'hourglass_top',
        'keys'  => [
            'pending.page_title'   => 'Registration Pending',
            'pending.title_1'      => 'Registration',
            'pending.title_2'      => 'Pending',
            'pending.subtitle'     => 'Your account is awaiting approval.',
            'pending.almost'       => 'Almost there!',
            'pending.desc_1'       => 'Your registration has been received. An administrator will review your account and approve it shortly.',
            'pending.desc_2'       => "You'll be able to log in once your account is approved.",
            'pending.back'         => 'Back to Login',
            'pending.help'         => 'Need help?',
            'pending.contact'      => 'Contact Support',
        ],
    ],

    'errors' => [
        'label' => 'Errors & Popups',
        'icon'  => 'report',
        'keys'  => [
            'error.403_title'   => 'Access Denied',
            'error.403_desc'    => "You don't have permission to view this page. If you believe this is a mistake, please contact your teacher.",
            'error.404_title'   => 'Page Not Found',
            'error.404_desc'    => "The page you are looking for doesn't exist or has been moved.",
            'error.419_title'   => 'Session Expired',
            'error.419_desc'    => 'Your session has expired. Refresh the page and try again.',
            'error.429_title'   => 'Too Many Requests',
            'error.429_desc'    => "You've been moving too fast! Please wait a moment and try again.",
            'error.500_title'   => 'Something Went Wrong',
            'error.500_desc'    => 'An unexpected error occurred on our side. Please try again later.',
            'error.503_title'   => 'Service Unavailable',
            'error.503_desc'    => "We're doing some quick maintenance right now. Please check back soon.",
            'error.500_fallback_title' => 'Something Went Wrong',
            'error.500_fallback_desc'  => 'An unexpected error occurred. Please try again.',
            'error.go_home'     => 'Go Home',
            'error.back_exams'  => 'Back to Exams',
            'success.title'     => 'Feedback Received!',
            'success.desc'      => 'Your review has been successfully sent to Teacher Roya. Thank you for helping us improve our galaxy!',
            'success.continue'  => 'Continue Journey',
            'card.details'      => 'Details',
            'card.mission_progress' => 'Mission Progress',
            'card.ready_status' => 'Ready Status',
        ],
    ],

    'welcome' => [
        'label' => 'Welcome (Post-Registration)',
        'icon'  => 'celebration',
        'keys'  => [
            'welcome.page_title'      => 'Welcome Star Student',
            'welcome.title_1'         => "You're a",
            'welcome.title_hl'        => 'Star',
            'welcome.title_2'         => 'Now!',
            'welcome.desc'            => 'Your registration is successfully completed. Start your first lesson now by choosing an option below!',
            'welcome.learn_title'     => 'Start Learning',
            'welcome.learn_desc'      => 'First Topic: Nouns',
            'welcome.profile_title'   => 'Setup Profile',
            'welcome.profile_desc'    => 'Set your avatar',
            'welcome.footer_hint'     => 'Navigate through the grammar galaxies using the navigation bar below',
        ],
    ],
];
